apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-image
spec:
  params:
    - name: dataPath
  steps:
    - name: get-secrets
      image: quay.io/chuang/release-service-utils
      script: |
        set -eux

        DATA_FILE="$(workspaces.data.path)/$(params.dataPath)/data.json"
        if [ ! -f "${DATA_FILE}" ] ; then
            echo "No data JSON was provided."
            exit 1
        fi

        jq -jr '.pushOptions.pushKeytab.secret' $DATA_FILE > $(results.secret.path)
      workingDir: $(workspaces.data.path)
  workspaces:
    - name: data
  results:
    - name: secret
      type: string
      description: |
        The string of the secrets to store the keytabs and oras login info
